apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  provider: kubernetes
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  progressDeadlineSeconds: 180
  service:
    port: 9898
    targetPort: 9898
  analysis:
    interval: 20s
    threshold: 2
    iterations: 3
    webhooks:
    - name: load-test
      url: http://flagger-loadtester.flagger-system/
      timeout: 5s
      metadata:
        cmd: "hey -z 15s -q 5 -c 2 http://podinfo-canary.{{ .Release.Namespace }}:9898/"
    - name: acceptance-test
      type: pre-rollout
      url: http://flagger-loadtester.flagger-system/
      timeout: 30s
      metadata:
        type: bash
        cmd: "curl -sd 'ok' http://podinfo-canary.{{ .Release.Namespace }}:9898/token | grep -q token"
